#!/bin/bash
#PBS -N exp_gap2
#PBS -P scai
#PBS -q scai_q
#PBS -l select=1:ncpus=4:ngpus=1:mem=120gb
#PBS -l walltime=00:45:00
PY=$HOME/scratch/miniconda3/envs/amlc312/bin/python
export AMLC_ROOT=/scratch/scai/mtech/aib262045/amlc_exp OMP_NUM_THREADS=4 PYTHONPATH=$HOME/scratch/ber_gen_code/ber/src DFOLD=1
cd $HOME/scratch/ber_gen_code/ber/src
$PY -u $HOME/scratch/exp/exp6.py
echo "done $(date +%T)"
